services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@local
      POSTGRES_DB: books-service
    ports:
      - "55432:5432"


  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres@local
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9009:8080"
    depends_on:
      - db
    networks:
      - observability

  livros-service:
    build: .
    ports:
      - "9191:9191"
    depends_on:
      - db
    environment:
      - JAEGER_HOST=jaeger-identity
      - JAEGER_PORT=4317
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/books-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres@local
    networks:
      - observability

volumes:
  postgres_data:

networks:
  observability:
    driver: bridge