services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@local
      POSTGRES_DB: books-service
    ports:
      - "55432:5432"

  livros-service:
    build: .
    ports:
      - "9191:9191"
    depends_on:
      - db
    environment:
      - JAEGER_HOST=jaeger-identity
      - JAEGER_PORT=4317
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/books-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres@local
      - JWT_ISSUER_URI=${JWT_ISSUER_URI}
    networks:
      - observability

volumes:
  postgres_data:

networks:
  observability:
    external: true