services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@local
      POSTGRES_DB: books-service
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-service
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - ./data/jaeger:/badger

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres@local
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9009:8080"
    depends_on:
      - db

  livros-service:
    build: .
    ports:
      - "9191:9191"
    depends_on:
      - db

volumes:
  postgres_data: